ManufacturingManagement_V2/Controllers/TreeviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManufacturingManagement_V2.Models;
using System.Configuration;
using System.Data.SqlClient;

namespace ManufacturingManagement_V2.Controllers
{
    public class TreeviewController : Controller
    {
        private readonly clsCookie objCookie = new clsCookie();
        private readonly clsMyClass mc = new clsMyClass();
        private readonly CompanyBLL compBLL = new CompanyBLL();
        private readonly EmployeeBLL empBLL = new EmployeeBLL();

        private void SetViewData()
        {
            ViewData["UserName"] = objCookie.getUserName();
            ViewData["CompName"] = objCookie.getCmpName();
            ViewData["FinYear"] = objCookie.getFinYear();
            ViewData["Dept"] = objCookie.getDepartment();
        }
        //
        // GET: /Treeview/

        AAA_SiteMenu_BLL lists = new AAA_SiteMenu_BLL();

        public ActionResult Index()
        {
            if (objCookie.checkSessionState() == false) { return RedirectToAction("LoginUser", "Login"); };
            SetViewData();

            List<Menu_MenuName> all = new List<Menu_MenuName>();
            using (ErpConnection dc = new ErpConnection())
            {
                all = dc.Menu_MenuName.OrderBy(a => a.ParentMenuId).ToList();
            }
            return View(all);
        }

       
        //public PartialViewResult _Index()
        //{

        //    return PartialView();
        //}
      
        public ActionResult ParentList()
        {
            if (objCookie.checkSessionState() == false) { return RedirectToAction("LoginUser", "Login"); };
            SetViewData();
            //ViewBag.CompanyList = new SelectList(Lists.get_Item_Type_ITCell(), "Item_Type_Id", "Item_Type", objCookie.getCompCode());
            ModelState.Clear();
            Menu_MenuName model = new Menu_MenuName
            {
                Item_List = lists.Get_ParentMenu_List()
            };
            return View(model);
        }


        public JsonResult Edit_ParentMenu_Record(int? id)
        {

            var hl = lists.Get_ParentMenu_List().Find(x => x.ParentMenuId.Equals(id));
            return Json(hl, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult Edit_ParentMenu(Menu_MenuName objModel)
        {
            try
            {
                int result = lists.Update_ParentMenu(objModel);
                if (result == 1)
                {
                    ViewBag.Message = "Record Updated Successfully";

                    ModelState.Clear();
                }
                else
                {
                    ViewBag.Message = "Unsucessfull";
                    ModelState.Clear();
                }

                return RedirectToAction("ParentList");
            }
            catch
            {
                throw;
            }
        }



        [HttpPost]
        public ActionResult Add_ParentMenu(Menu_MenuName objModel)
        {
            try
            {
                int result = lists.Insert_ParentMenu(objModel);
                if (result == 1)
                {
                    ViewBag.Message = "Record Updated Successfully";

                    ModelState.Clear();
                }
                else
                {
                    ViewBag.Message = "Unsucessfull";
                    ModelState.Clear();
                }

                return RedirectToAction("ParentList");
            }
            catch
            {
                throw;
            }
        }












    }
}

ManufacturingManagement_V2/Views/Treeview/Index.cshtml
@model List<ManufacturingManagement_V2.Models.Menu_MenuName1>
@{
     Layout = null;
    ViewBag.Title = "Simple";
}
<h2>Menu Hierarchy</h2>
<style>
    /*Here We will add some css for style our treeview*/
    .collapse {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -36px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .expand {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -50px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .treeview ul {
        font: 14px Arial, Sans-Serif;
        margin: 0px;
        padding-left: 20px;
        list-style: none;
    }

    .treeview > li > a {
        font-weight: bold;
    }

    .treeview li {
    }

        .treeview li a {
            padding: 4px;
            font-size: 12px;
            display: inline-block;
            text-decoration: none;
            width: auto;
        }
</style>
<div style="border:solid 1px black; padding:10px;background-color:#FAFAFA;width:300px;color:black;">
    <div class="treeview">
        @if (Model != null && Model.Count() > 0)
        {
            <ul>
                @TreeView.GetTreeView(Model, Model.FirstOrDefault().ParentMenuId)
            </ul>
        }
    </div>
</div>

@*background-color:#FAFAFA*@

@* Here We need some Jquery code for make this treeview collapsible *@
@section Scripts{
    <script>
        $(document).ready(function () {
            $(".treeview li>ul").css('display', 'none'); 
            $(".collapsible").click(function (e) {
                e.preventDefault();
                $(this).toggleClass("collapse expand");
                $(this).closest('li').children('ul').slideToggle();
            });
        });

    </script>
}

ManufacturingManagement_V2/Views/Treeview/ParentList.cshtml
@model ManufacturingManagement_V2.Models.Menu_ManuName
@{
    ViewBag.Title = "Index";
 }
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <script type="text/javascript" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script>
        $(function () {
            $('#example1').DataTable();
        })
        function GetDetails(id) {
            $.ajax({
                url: "/Treeview/Edit_ParentMenu_Record/" + id,
                typr: "GET",
                contentType: "application/json;charset=UTF-8",
                dataType: "json",
                success: function (response) {
                    $('#ParentMenuId').val(response.ParentMenuId);
                    $('#ParentMenuName').val(response.ParentMenuName);
                    $('#modal-Update').modal('show');
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
            return false;
        }
    </script>
</head>

<body style="background-color:lightgray">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                    </div>
                    <div class="box-body">

                        <div style="color:black;background-color:lightgray;width:1100px">
                           @* @Html.ActionLink("Back To Home", "../Treeview/Index")*@
                            @* @Html.ActionLink("Item Type", "../B_ITAssestCell/Index")|
                                @Html.ActionLink("Item Master", "../B_Item_Master_ItCell/Index")|
                                @Html.ActionLink("Add in Stock ", "../Add_In_Stock_ITCELLLis/Index")|
                                @Html.ActionLink("Issue Item", "../B_Issue_Item_ITCELLList/Index")|
                                @Html.ActionLink("Mark Scrap Item", "../B_Scrap_Item/Index")|
                                @Html.ActionLink("Approve Scrap Item", "../B_GetApproval_ScrapItem/Index")|
                                @Html.ActionLink("Upload Invoice/Doc", "../B_Upload_Invoice_ITCEll/Index")|
                                @Html.ActionLink("Download Invoice/Doc", "../B_GetInvoiceDetail/Index")*@
                        </div>
                        @if (ViewBag.Message != null)
                        {
                            <div class="alert alert-success alert-dismissable">
                                @ViewBag.Message;
                                <a href="#" class="close" data-dissmiss="alert">x</a>
                            </div>
                        }


                        <table id="example1" class="table table-bordered table-hover " style="background-color:lightgray; width:1100px" ">
                            <thead>
                                <tr>
                                    <th>Parent Id/th>
                                    <th>Parent Menu Name</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Item_List)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(model => item.ParentMenuId)</td>
                                        <td>@Html.DisplayFor(model => item.ParentMenuName)</td>

                                        <td>
                                            <a onclick="GetDetails(@item.ParentMenuID)">
                                                <i class="fa fa-edit">
                                                </i>
                                            </a>
                                            @*<a style="color:black">
                                                @Html.ActionLink("", "RemoveEmployee", "B_ITAssestCell", new { Id = item.Item_Type_Id }, new { onclick = "return confirm('Are  sure wants to delete?');", @class = "fa fa-trash-o" })
                                                </a>*@
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="modal fade" id="modal-Update">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header with-border">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="box-title"> Update Parent Menu </h3>
                </div>
                <div class="modal-body">
                    <div class="box box-primary">
                        @using (Html
                            .BeginForm("Edit_ParentMenu", "Treeview", FormMethod.Post))
                        {
                            <div class="modal-body">
                                <div class="col-md-8">
                                    <div class="form-group">
                                        <input type="number" class="form-control" id="ParentMenuID" name="ParentMenuID">
                                        <input type="text" class="form-control" id="ParentMenuName" name="ParentMenuName">
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modal-Insert" style="margin-right:20px;font-size:medium;">
        Add New Parent
    </button>

    <div class="modal fade" id="modal-Insert">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header with-border">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="box-title"> Add New Record</h3>
                </div>
                <div class="modal-body">
                    <div class="box box-primary">
                        @using (Html.BeginForm("Add_ParentMenu", "Treeview", FormMethod.Post))
                        {
                            <div class="modal-body">
                                <div class="col-md-8">
                                    <div class="form-group">

                                        <label>Item Type</label>

                                        @*<input  class="form-control text-box single-line input-validation-error" data-val="true" data-val-date="The field  must be a String." data-val-required="The Item_Type field is required." id="Item_Type_Item" name="Item_Type_Item" type="text" value="NA" aria-required="true" aria-describedby="Item_Type-error" aria-invalid="true" />*@

                                        @Html.TextBoxFor(model => model.ParentMenuName, new { @class = "form-control", @placeholder = "ParentMenuName" })
                                        @Html.ValidationMessageFor(model => model.ParentMenuName, "", new { @class = "error" })

                                    </div>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="submit" class="btn btn-success">Submit</button>

                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div>
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-success alert-dismissable">
                @ViewBag.Message;
                <a href="#" class="close" data-dissmiss="alert">x</a>
            </div>
        }
    </div>

</body>
</html>

ManufacturingManagement_V2/Views/Treeview/Simple.cshtml
@model List<ManufacturingManagement_V2.Models.SiteMenu>
@{
    
    Layout = "~/views/shared/MyLayout.cshtml";
    ViewBag.Title = "Simple";
}
<style>
    /*Here We will add some css for style our treeview*/
    .collapse {
        width:15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -36px -17px;
        display:inline-block;
        cursor:pointer;
    }
    .expand {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -50px -17px;
        display: inline-block;
        cursor:pointer;
    }
    
     .treeview ul
        {
            font:14px Arial, Sans-Serif;
            margin:0px;
            padding-left:20px;
            list-style:none;
        }
        .treeview > li > a {
            font-weight:bold;
        }
        .treeview li
        {
               
        }
        .treeview li a
        {
            padding:4px;
            font-size:12px;
            display:inline-block;
            text-decoration:none;
            width:auto;
        }
</style>
<h2>Simple Treeview from Database Data</h2>
<div style="border:solid 1px black; padding:10px; background-color:#FAFAFA">
    <div class="treeview">
        @if (Model != null && Model.Count() >0)
        {
            <ul>
                @TreeView.GetTreeView(Model,Model.FirstOrDefault().ParentMenuID)
            </ul>
        }
    </div>
</div>

@* Here We need some Jquery code for make this treeview collapsible *@
@section Scripts{
    <script>
        $(document).ready(function () {
            $(".treeview li>ul").css('display', 'none'); // Hide all 2-level ul 
            $(".collapsible").click(function (e) {
                e.preventDefault();
                $(this).toggleClass("collapse expand");
                $(this).closest('li').children('ul').slideToggle();
            });
        });
    </script>
}

ManufacturingManagement_V2/Views/Treeview/_Simple.cshtml
@model List<ManufacturingManagement_V2.Models.SiteMenu>
@{

    Layout = "~/views/shared/MyLayout.cshtml";
    ViewBag.Title = "Simple";
}
<style>
    /*Here We will add some css for style our treeview*/
    .collapse {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -36px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .expand {
        width: 15px;
        background-image: url('../Images/ui-icons_454545_256x240.png');
        background-repeat: no-repeat;
        background-position: -50px -17px;
        display: inline-block;
        cursor: pointer;
    }

    .treeview ul {
        font: 14px Arial, Sans-Serif;
        margin: 0px;
        padding-left: 20px;
        list-style: none;
    }

    .treeview > li > a {
        font-weight: bold;
    }

    .treeview li {
    }

        .treeview li a {
            padding: 4px;
            font-size: 12px;
            display: inline-block;
            text-decoration: none;
            width: auto;
        }
</style>
<h2>Simple Treeview from Database Data</h2>
<div style="border:solid 1px black; padding:10px; background-color:#FAFAFA">
    <div class="treeview">
        @if (Model != null && Model.Count() > 0)
        {
            <ul>
                @TreeView.GetTreeView(Model, Model.FirstOrDefault().ParentMenuID)
            </ul>
        }
    </div>
</div>

@* Here We need some Jquery code for make this treeview collapsible *@
@section Scripts{
    <script>
        $(document).ready(function () {
            $(".treeview li>ul").css('display', 'none'); // Hide all 2-level ul
            $(".collapsible").click(function (e) {
                e.preventDefault();
                $(this).toggleClass("collapse expand");
                $(this).closest('li').children('ul').slideToggle();
            });
        });
    </script>
}