ManufacturingManagement_V2/Controllers/SaleInvoiceReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Reporting.WebForms;
using ManufacturingManagement_V2.Models;
using System.Data;
using QRCoder;
using System.IO;
using System.Drawing.Imaging;
using System.Xml.Serialization;
using System.Xml;
using System.Collections;

namespace ManufacturingManagement_V2.Controllers
{
    public class SaleInvoiceReportController : Controller
    {
        clsCookie objCookie = new clsCookie();
        clsMyClass mc = new clsMyClass();
        CompanyBLL compBLL = new CompanyBLL();
        //
        // GET: /AttendanceReport/
        private void setViewData()
        {
            ViewData["UserName"] = objCookie.getUserName();
            ViewData["CompName"] = objCookie.getCmpName();
            ViewData["FinYear"] = objCookie.getFinYear();
            ViewData["Dept"] = objCookie.getDepartment();
            ViewData["mnuOpt"] = objCookie.getMenu();
        }

        public ActionResult Index()
        {
            if (objCookie.checkSessionState() == false) { return RedirectToAction("LoginUser", "Login"); };
            setViewData();
            rptOptionMdl rptOption = new rptOptionMdl();
            ViewBag.CompanyList = new SelectList(compBLL.getObjectList(), "compcode", "cmpname");
            ViewBag.FinYearList = new SelectList(compBLL.getFinancialYear(), "finyear", "finyear");
            rptOption.CompCode = Convert.ToInt32(objCookie.getCompCode());
            return View(rptOption);
        }
            
        #region Sale Invoice Report
        [HttpGet]
        public ActionResult DisplaySaleInvoice(int salerecid = 0, string chinv = "i")
        {
            if (objCookie.checkSessionState() == false) { return RedirectToAction("LoginUser", "Login"); };
            setViewData();
            bool viewper = mc.getPermission(Entry.Sales_Report, permissionType.Add);
            if (viewper == false)//no permission
            {
                return Content("<a href='#' onclick='javascript:window.close();'><h1>Permission Denied!</h1></a>");
            }
            bool downloadper = mc.getPermission(Entry.Sales_Report, permissionType.Edit);
            Session["xsid"] = objCookie.getUserId();
            if (viewper == true && downloadper == false)//view only
            {
                string reporturl = "SaleInvoiceReport/getSaleInvoiceReport";
                string reportpms = "salerecid=" + salerecid + "";
                reportpms += "chinv=" + chinv + "";
                return RedirectToAction("IndexIFrameRpt", "Home", new { reporturl = reporturl, reportpms = reportpms });
            }
            //full access with download (no escalation)
            return RedirectToAction("getSaleInvoiceReport", new { salerecid = salerecid, chinv = chinv });
        }

        [HttpGet]
        public ActionResult getSaleInvoiceReport(int salerecid, string chinv = "i")
        {
            if (mc.isValidToDisplayReport() == false)
            {
                return Content("<a href='#' onclick='javascript:window.close();'><h1>Permission Denied!</h1></a>");
            }
            if (salerecid == 0)
            {
                return Content("<a href='#' onclick='javascript:window.close();'><h1>Invoice number not selected!</h1></a>");
            }
            //
            SaleBLL sbll = new SaleBLL();
            SaleMdl smdl = sbll.searchObject(salerecid);
            //
            CrystalDecisions.CrystalReports.Engine.ReportDocument rptDocHeader = new CrystalDecisions.CrystalReports.Engine.ReportDocument();
            CrystalDecisions.CrystalReports.Engine.ReportDocument rptDocLedger = new CrystalDecisions.CrystalReports.Engine.ReportDocument();
            if (smdl.InvoiceMode.ToLower() == "dbn" || smdl.InvoiceMode.ToLower() == "cdn")
            {
                rptDocHeader.Load(System.IO.Path.Combine(Server.MapPath("~/Reports/SaleInvoiceRPT/"), "DnCnHeader.rpt"));
                rptDocLedger.Load(System.IO.Path.Combine(Server.MapPath("~/Reports/SaleInvoiceRPT/"), "DnCnLedger.rpt"));
            }
            else
            {
                if (chinv.ToLower() == "i")
                {
                    rptDocHeader.Load(System.IO.Path.Combine(Server.MapPath("~/Reports/SaleInvoiceRPT/"), "InvoiceHeader.rpt"));
                    rptDocLedger.Load(System.IO.Path.Combine(Server.MapPath("~/Reports/SaleInvoiceRPT/"), "InvoiceLedger.rpt"));
                }
                else if (chinv.ToLower() == "c")
                {
                    rptDocHeader.Load(System.IO.Path.Combine(Server.MapPath("~/Reports/SaleInvoiceRPT/"), "ChallanHeader.rpt"));
                    rptDocLedger.Load(System.IO.Path.Combine(Server.MapPath("~/Reports/SaleInvoiceRPT/"), "ChallanLedger.rpt"));
                }
            }
            setLoginInfo(rptDocHeader);
            //
            //CrystalDecisions.CrystalReports.Engine.TextObject txtNumToWords = (CrystalDecisions.CrystalReports.Engine.TextObject)rptDocSub1.ReportDefinition.Sections["PageHeaderSection2"].ReportObjects["txtNumToWords"];
            //txtNumToWords.Text = mc.getWordByNumericDouble(smdl.NetAmount.ToString());
            //dbp parameters
            rptDocHeader.SetParameterValue("@salerecid", salerecid);//header
            //also rptDocMain.Subreports[Index].Name.ToString() can be used for sub-reports
            if (smdl.InvoiceMode.ToLower() == "dbn" || smdl.InvoiceMode.ToLower() == "cdn")
            {
                rptDocHeader.SetParameterValue("@salerecid", salerecid, "DnCnLedger.rpt");
            }
            else
            {
                if (chinv.ToLower() == "i")
                {
                    rptDocHeader.SetParameterValue("@salerecid", salerecid, "InvoiceLedger.rpt");
                }
                else if (chinv.ToLower() == "c")
                {
                    rptDocHeader.SetParameterValue("@salerecid", salerecid, "ChallanLedger.rpt");
                }
            }
            //additional parameters --defined in crpt with @name/static
            rptDocHeader.SetParameterValue("@NumToWords", mc.getWordByNumericDouble(smdl.NetAmount.ToString()));
            //
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            //rd.RecordSelectionFormula = "";
            System.IO.Stream stream = null;
            try
            {
                stream = rptDocHeader.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            }
            catch (Exception ex)
            {
                string st = ex.Message;
            }
            finally
            {
                rptDocHeader.Close();
                rptDocLedger.Close();
            }
            //add these lines to download
            //stream.Seek(0, System.IO.SeekOrigin.Begin);
            //return File(stream, "application/pdf", "ReportName.pdf");
            return File(stream, "application/pdf");
        }
        #endregion

        #region Eformat - invoice report 

        [HttpPost]
        public ActionResult DisplayInvoice(rptOptionMdl rptOption)
        {
            //[100171]
            if (objCookie.checkSessionState() == false) { return RedirectToAction("LoginUser", "Login"); };
            setViewData();
            bool viewper = mc.getPermission(Entry.Sales_Report, permissionType.Add);
            if (viewper == false)//no permission
            {
                return Content("<a href='#' onclick='javascript:window.close();'><h1>Permission Denied!</h1></a>");
            }
            bool downloadper = mc.getPermission(Entry.Sales_Report, permissionType.Edit);
            Session["xsid"] = objCookie.getUserId();
            if (viewper == true && downloadper == false)//view only
            {
                string reporturl = "SaleInvoiceReport/getInvoiceReport";
                string reportpms = "salerecid=" + rptOption.SaleRecId + "";
                return RedirectToAction("IndexIFrameRpt", "Home", new { reporturl = reporturl, reportpms = reportpms });
            }
            //full access with download (no escalation)
            return RedirectToAction("getInvoiceReport", new { salerecid = rptOption.SaleRecId });
        }

        [HttpGet]
        public ActionResult DisplayInvoiceForV1(int salerecid = 0)
        {
            //[100171]
            if (objCookie.checkSessionState() == false) { return RedirectToAction("LoginUser", "Login"); };
            setViewData();
            bool viewper = mc.getPermission(Entry.Sales_Report, permissionType.Add);
            if (viewper == false)//no permission
            {
                return Content("<a href='#' onclick='javascript:window.close();'><h1>Permission Denied!</h1></a>");
            }
            bool downloadper = mc.getPermission(Entry.Sales_Report, permissionType.Edit);
            Session["xsid"] = objCookie.getUserId();
            if (viewper == true && downloadper == false)//view only
            {
                string reporturl = "SaleInvoiceReport/getInvoiceReport";
                string reportpms = "salerecid=" + salerecid + "";
                return RedirectToAction("IndexIFrameRpt", "Home", new { reporturl = reporturl, reportpms = reportpms });
            }
            //full access with download (no escalation)
            return RedirectToAction("getInvoiceReport", new { salerecid = salerecid });
        }

        [HttpGet]
        public ActionResult getInvoiceReport(int salerecid)
        {
            //string irn = "142110245514291c72d74cbda0a122a088df23141331875316808a3e5ad4d65c41af41dabf71dae";
            //SaleMdl slMdl = new SaleMdl();
            //SaleBLL slBll = new SaleBLL();
            //slMdl = slBll.searchObject(salerecid);
            //string irn = slMdl.InvReferenceNo;
            //using (MemoryStream ms = new MemoryStream())
            //{

ManufacturingManagement_V2/Views/SaleInvoiceReport/GetJSonForIRN.cshtml
@{
    ViewBag.Title = "XML EInvoice";
    //Layout = "~/Views/Shared/_LayoutCommon.cshtml";
}

@*<h4><b>E Invoice XML</b></h4>*@
@ViewBag.Message

ManufacturingManagement_V2/Views/SaleInvoiceReport/Index.cshtml
@model ManufacturingManagement_V2.Models.rptOptionMdl

@{
    ViewBag.Title = "Index";
    Layout = "~/views/shared/_LayoutCommon.cshtml";
}

<h4><b>Sale Invoice Report</b></h4>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <div class="form-group">
        <h5><b>Report Options</b></h5>
        <table class="table table-bordered">
            @Html.HiddenFor(model => model.SaleRecId)
            <tr>
                <td style="width:10%;"><b>Company</b></td>
                <td>@Html.DropDownListFor(model => model.CompCode, ViewBag.CompanyList as SelectList)</td>
            </tr>
            <tr>
                <td><b>Financial&nbsp;Year</b></td>
                <td>
                    @Html.DropDownListFor(model => model.FinYear, ViewBag.FinYearList as SelectList)
                </td>
            </tr>
            <tr>
                <td><b>Invoice No</b></td>
                <td>
                    @Html.EditorFor(model => model.InvoiceNo)
                <label id="lblSaleRecId" style="font-weight:normal;"></label>
            </td>
        </tr>
        </table>
    </div>
    <p>
        <input type="submit" class="btn btn-default" value="Invoice" style="width:150px;" onclick="target = '_blank';"
               formaction="@Url.Action("DisplayInvoice")" />
        <input type="submit" class="btn btn-default" value="Challan" style="width:150px;" onclick="target = '_blank';"
               formaction="@Url.Action("DisplayInvoice")" />
        <br /><input type="submit" class="btn btn-default" value="Download Invoice Excel for Tally" style="width:305px;" onclick="target = '_blank';"
                     formaction="@Url.Action("getEInvoiceExcel")" />
        <br />@Html.ActionLink("Upload IRN Detail XML from Tally", "UploadIRNDetail", "InvoiceControl", null,
                new { id = "mylinkUpload", @target="_new;", @class = "btn btn-default", @style = "width:305px;" })
        <br />@Html.ActionLink("View Updated IRN", "UpdateIRNDetail", "InvoiceControl", null,
                new { id = "mylinkUpdate", @target = "_new;", @class = "btn btn-default", @style = "width:305px;" })
        <br /><br /><a href="/Home/DisplayErpV1?url=../Edit/SaleEntryEdt.aspx">
            <span style="color:blue;">
                <b><u>Invoice/Challan in Old Format (F.Y. upto 2020-21)</u></b>
            </span>
        </a>
    </p>
    <h5><b>@ViewBag.Message</b></h5>
}

@section Scripts{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript">
        $(function () {
            $("input[type=text]").first().focus();
            //document.getElementById("txtAttDay").focus();
            $("#InvoiceNo").attr("placeholder", "start typing, then select");
            //$('#mylinkUpload').attr('href', '#');
            //$('#mylinkUpdate').attr('href', '#');
        });
    </script>

    <script type="text/javascript">
        $("#InvoiceNo").autocomplete({
            source: function (request, response) {
                var liCCode = document.getElementById("CompCode");
                var indexCCode = liCCode.selectedIndex;
                var ccode = liCCode.options[indexCCode].value;
                var liFinYr = document.getElementById("FinYear");
                var indexFinYr = liFinYr.selectedIndex;
                var finyr = liFinYr.options[indexFinYr].value;
                var customer = new Array();
                $.ajax({
                    async: false,
                    cache: false,
                    type: "POST",
                    url: "@(Url.Action("AutoCompleteInvoiceNumbers", "SaleInvoiceReport"))",
                    data: { "term": request.term, "ccode": ccode, "finyr": finyr },
                    success: function (data) {
                        for (var i = 0; i < data.length ; i++) {
                            customer[i] = { label: data[i].Value, Id: data[i].Key };
                        }
                    }
                });
                response(customer);
            }, minLength: 2,
            select: function (event, ui) {
                document.getElementById('SaleRecId').value = ui.item.Id;
                $('#lblSaleRecId').text('Sale RecId: ' + ui.item.Id);
                $('#mylinkUpload').attr('href', '/InvoiceControl/UploadIRNDetail' + '?salerecid=' + ui.item.Id + '&invoiceno=' + ui.item.label);
                $('#mylinkUpdate').attr('href', '/InvoiceControl/UpdateIRNDetail' + '?id=' + ui.item.Id);
            }
        });
    </script>

}