ManufacturingManagement_V2/Controllers/WipToRg1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManufacturingManagement_V2.Models;

namespace ManufacturingManagement_V2.Controllers
{
    //modified-from-StockController
    public class WipToRg1Controller : Controller
    {
        clsCookie objCookie = new clsCookie();
        clsMyClass mc = new clsMyClass();
        private StockBLL bllObject = new StockBLL();
        private ItemBLL itemBLL = new ItemBLL();
        private StockLedgerBLL lgrBLL = new StockLedgerBLL();

        private void setViewData()
        {
            ViewData["UserName"] = objCookie.getUserName();
            ViewData["CompName"] = objCookie.getCmpName();
            ViewData["FinYear"] = objCookie.getFinYear();
            ViewData["Dept"] = objCookie.getDepartment();
            ViewData["mnuOpt"] = objCookie.getMenu();
        }

        private void setViewObject(string dtfrom = "", string dtto = "")
        {
            ViewBag.DtFrom = dtfrom;
            ViewBag.DtTo = dtto;
        }

        public ActionResult Index(string dtfrom = "", string dtto = "")
        {
            if (mc.getPermission(Entry.WipToRg1_Entry, permissionType.Add) == false)
            {
                return Content("<a href='#' onclick='javascript:window.close();'><h1>Permission Denied!</h1></a>");
            }
            setViewData();
            if (dtfrom.Length == 0) { dtfrom = mc.getStringByDate(objCookie.getFromDate()); };
            if (dtto.Length == 0) { dtto = mc.getStringByDate(objCookie.getDispToDate()); };
            setViewObject(dtfrom, dtto);
            List<StockLedgerMdl> modelObject = new List<StockLedgerMdl> { };
            modelObject = lgrBLL.getStockLedgerListForStock("wrg1", dtfrom, dtto);//note:vtype=wrg1
            return View(modelObject.ToList());
        }

        [HttpPost]
        public ActionResult FilterIndex(FormCollection form)
        {
            string dtfrom = form["txtDtFrom"].ToString();
            string dtto = form["txtDtTo"].ToString();
            return RedirectToAction("Index", new { dtfrom = dtfrom, dtto = dtto });
        }

        // GET: /CreateUpdate
        public ActionResult CreateUpdate(int id = 0)
        {
            if (mc.getPermission(Entry.WipToRg1_Entry, permissionType.Add) == false)
            {
                return Content("<a href='#' onclick='javascript:window.close();'><h1>Permission Denied!</h1></a>");
            }
            setViewData();
            //
            ViewData["AddEdit"] = "Save";
            //note-this is by autocomplete now
            //ViewBag.ItemList = new SelectList(storeItemBLL.getObjectList(), "itemid", "itemname");
            //end-note
            ViewBag.UnitList = new SelectList(itemBLL.getItemUnitList(), "unit", "unitname");
            ViewBag.VDate = mc.getStringByDate(DateTime.Now);
            //
            StockMdl modelObject = new StockMdl();
            modelObject = bllObject.searchObject(id);
            if (modelObject.RecId > 0)
            {
                ViewData["AddEdit"] = "Update";
            }
            return View(modelObject);
        }

        // POST: /CreateUpdate
        [HttpPost]
        public JsonResult CreateUpdate(StockMdl modelObject)
        {
            if (objCookie.checkSessionState() == false)
            {
                return new JsonResult { Data = new { status = false, message = "Session expired! Login again." } };
            }
            if (modelObject.VType.ToLower() != "wrg1")
            {
                return new JsonResult { Data = new { status = false, message = "Invalid attempt!" } };
            }
            bllObject = new StockBLL();
            modelObject.VType = "wrg1";//note
            if (modelObject.RecId == 0)//add mode
            {
                if (mc.getPermission(Entry.WipToRg1_Entry, permissionType.Add) == false)
                {
                    return new JsonResult { Data = new { status = false, message = "Permission Denied!", AddEdit = "Save" } };
                }
                bllObject.insertObject(modelObject);//note
            }
            else//edit mode
            {
                if (mc.getPermission(Entry.WipToRg1_Entry, permissionType.Edit) == false)
                {
                    return new JsonResult { Data = new { status = false, message = "Permission Denied!", AddEdit = "Update" } };
                }
                bllObject.updateObject(modelObject);//note
            }
            return new JsonResult { Data = new { status = bllObject.Result, message = bllObject.Message, AddEdit = "Save" } };
        }

        [HttpPost]
        public JsonResult Delete(int recid)
        {
            if (mc.getPermission(Entry.WipToRg1_Entry, permissionType.Delete) == false)
            {
                return new JsonResult { Data = new { status = false, message = "Permission Denied!", AddEdit = "Update" } };
            }
            if (recid == 0)
            {
                return new JsonResult { Data = new { status = true, message = "OK" } };//note
            }
            bllObject = new StockBLL();
            bllObject.deleteObject(recid);
            return new JsonResult { Data = new { status = bllObject.Result, message = bllObject.Message } };
        }

        protected override void Dispose(bool disposing)
        {
            bllObject.Dispose();
            base.Dispose(disposing);
        }

    }
}

ManufacturingManagement_V2/Views/WipToRg1/Index.cshtml
@model IEnumerable<ManufacturingManagement_V2.Models.StockLedgerMdl>

    @{
        ViewBag.Title = "Index";
        Layout = "~/views/shared/_LayoutCommon.cshtml";
    }

    <h4><b>WIP to RG1 List</b></h4>

    <fieldset>
        @using (Ajax.BeginForm("FilterIndex", "WipToRg1", new AjaxOptions { UpdateTargetId = "divFilter" }))
        {
            <div class="form-group">
                @Html.ActionLink("Create New", "CreateUpdate", null, new { @class = "btn btn-default" })

                &nbsp;&nbsp;&nbsp;From
                &nbsp;@Html.TextBox("txtDtFrom", null, new { @class = "datepicker", style = "width:90px;" })

                &nbsp;To
                &nbsp;@Html.TextBox("txtDtTo", null, new { @class = "datepicker", style = "width:90px;" })

                &nbsp;<button class="btn btn-default">Submit</button>
            </div>

        }
    </fieldset>

    <table class="tablecontainer" style="width:100%;">
        <tr>
            <th style="width:30px;">
                S.No.
            </th>
            <th style="width:50px;">
                @Html.DisplayNameFor(model => model.VNo)
            </th>
            <th style="width:25px;">
                @Html.DisplayNameFor(model => model.VDate)
            </th>
            <th style="width:auto;">
                @Html.DisplayNameFor(model => model.ItemCode)
            </th>
            <th style="width:100px;">
                Qty/Unit
            </th>
            <th style="width:auto;">
                @Html.DisplayNameFor(model => model.Remarks)
            </th>
            <th style="width:120px;">Links</th>
        </tr>
        @{int i = 1;}
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @i
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VNo)
                </td>
                <td>
                    @Html.ValueFor(model => item.VDate, "{0:dd/MM/yyyy}")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemCode)
                </td>
                <td>
                    @Html.ValueFor(modelItem => item.Qty, "{0:##,##,##,##,##0.00}")
                    <br />@Html.DisplayFor(modelItem => item.UnitName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Remarks)
                </td>
                <td>
                    <table style="border:none;">
                        <tr>
                            <td style="border:none;padding:0px;">
                                @Html.ActionLink("Edit", "CreateUpdate", new { id = item.RecId })
                            </td>
                            <td style="border:none;padding:0px;">
                                @Html.ActionLink("Preview", "../StockRegister/StockSlipReport",
                                new { stkrecid = item.RecId }, new { @target = "_new;" })
                            </td>
                        </tr>
                        <tr>
                            <td style="border:none;padding:0px;">
                                @Html.ActionLink("Delete", null, null, new { onclick = "deleteRecord('" + item.RecId + "')" })
                            </td>
                            <td style="border:none;padding:0px;">
                                @Html.ActionLink("ViewLog", "../EventLogReport/getLogDetail",
                                new { tblid = 34, pkval = item.RecId }, new { @target = "_blank" })
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            i++;
        }

    </table>

    @section Scripts{

        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <script type="text/javascript">
        $(function () {
            //$("input[type=text]").first().focus();
            //document.getElementById("txtAttDay").focus();
            document.getElementById("txtDtFrom").value = '@ViewBag.DtFrom';
            document.getElementById("txtDtTo").value = '@ViewBag.DtTo';
        });
        </script>
        <script type="text/javascript">
            $(".datepicker").datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: "dd/mm/yy"
            });
        </script>

        <script>
            function deleteRecord(recid) {
                var a = confirm("Are you sure to delete this voucher?");
                if (a == false) {
                    return;
                }
                var data = {
                    recid: recid
                }
                $.ajax({
                    url: '/WipToRg1/Delete',
                    type: "POST",
                    data: JSON.stringify(data),
                    dataType: "JSON",
                    contentType: "application/json",
                    success: function (d) {
                        alert(d.message);
                        if (d.status == true) {
                            location.reload();
                        }
                    }
                });
            }
        </script>

    }